---
- name: Provision some VMs
  hosts: localhost
  gather_facts: false
  vars:
    my_vms:
    - {vm_name: "{{ vm_name }}", vm_ip: "{{ vm_ip }}", vm_sn: "{{ vm_ipsubnet }}",vm_gw: "{{ vm_ipgateway }}",vm_dns: "{{ vm_dns }}",vm_ram: "{{ vm_ram }}", vm_num_cpu_per_socket: "{{ vm_cpu }}", vm_num_sockets: "{{ vm_sockets }}", vm_disk: "{{ vm_disk }}"}
  
 #     - {vm_name: "{{ vm_name }}", vm_ip: "{{ vm_ip }}", vm_ram: "{{ vm_ram }}", vm_num_cpu_per_socket: "{{ vm_soc }}", vm_num_sockets: "{{ vm_sockets }}", vm_disk_list: "{{ vm_disk1 }}"}
 #     - {vm_name: server2, vm_ip: '172.29.171.101', vm_ram: 4096, vm_num_cpu_per_socket: 1, vm_num_sockets: 4, vm_disk_list: [disk_size_mib: 76294, disk_size_mib: 152588]}
  tasks:
    - name: Provision VMs on Nutanix
      include_role:
        name: nutanix_vm_provisioner
      vars:
        vm_defs: "{{ my_vms }}"
